services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: es-mini
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports: ["9200:9200"]
    networks: [elk]

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana-mini
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    ports: ["5601:5601"]
    depends_on: [elasticsearch]
    networks: [elk]

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.0
    container_name: logstash-mini
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
      - XPACK_MONITORING_ENABLED=false
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ./logs:/logs:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    depends_on: [elasticsearch]
    networks: [elk]

networks:
  elk:
    driver: bridge
