# Docker Compose v2 schema
# Runs Elasticsearch, Kibana, Filebeat for mini-ELK demo

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: es-mini
    environment:
      # Single-node dev mode
      - discovery.type=single-node
      # Enable security (required in 8.x)
      - xpack.security.enabled=true
      # Set the built-in "elastic" superuser password on first boot
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      # Keep HTTP without TLS for local demo
      - xpack.security.http.ssl.enabled=false
    ports:
      - "${ES_HTTP}:9200"
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 60

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: kibana-mini
    depends_on:
      - elasticsearch
    environment:
      # Point Kibana to ES inside the compose network
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

      # 🔑 Auth using kibana_system user + password
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}

      # Basic server settings
      - xpack.security.enabled=true
      - server.publicBaseUrl=http://localhost:${KIBANA_HTTP}
      - server.host=0.0.0.0
    ports:
      - "${KIBANA_HTTP}:5601"

  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELASTIC_VERSION}
    container_name: filebeat-mini
    user: root
    depends_on:
      - elasticsearch
      - kibana
    command: ["--strict.perms=false", "-e"]
    environment:
      # Filebeat -> ES inside docker network
      - ELASTICSEARCH_HOST=elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ./filebeat.d/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/logs:ro
