filebeat.inputs: []
filebeat.modules:
  - module: nginx
    access:
      enabled: true
      var.paths: ["/logs/access.log"]
    error:
      enabled: true
      var.paths: ["/logs/error.log"]

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "${ELASTICSEARCH_USERNAME:elastic}"
  password: "${ELASTICSEARCH_PASSWORD}"

setup.template.enabled: false
setup.ilm.enabled: auto
logging.to_files: false
