# filebeat.d/filebeat.yml
# Minimal, module-only config that ships Nginx logs into ECS data streams: logs-nginx.*-default
logging.level: info

filebeat.modules:
  - module: nginx
    access:
      enabled: true
      # docker-compose mounts ./logs -> /logs in the container
      var.paths:
        - /logs/access.log
    error:
      enabled: true
      var.paths:
        - /logs/error.log

# Send directly to Elasticsearch
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"

  # IMPORTANT: enable data streams so Beats writes to logs-<dataset>-<namespace>
  data_stream:
    enabled: true
    namespace: "default"

# When using data streams, disable legacy templates/ILM
setup.template.enabled: false
setup.ilm.enabled: false

# (Optional but nice): add cloud-ish metadata
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_fields:
      target: ecs
      fields:
        version: "8.0.0"
